webtalk_init -webtalk_dir /home/fel/Vivado_Projects/wSumIntegration/wSumIntegration.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Dec 14 18:21:19 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "i386" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211101974_0_0_504" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4pjavro4jc9roo3fvchsa7gd0b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3410.010 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1450113329000" -context "sdk\\\\hardware/1450113329000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1450113329000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1450113329000"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1450113329000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1450113329000"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1450113329000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1450113329000"
webtalk_add_data -client sdk -key uid -value "1450113442000" -context "sdk\\\\bsp/1450113442000"
webtalk_add_data -client sdk -key hwid -value "1450113329000" -context "sdk\\\\bsp/1450113442000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1450113442000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1450113442000"
webtalk_add_data -client sdk -key uid -value "1450113444000" -context "sdk\\\\application/1450113444000"
webtalk_add_data -client sdk -key hwid -value "1450113329000" -context "sdk\\\\application/1450113444000"
webtalk_add_data -client sdk -key bspid -value "1450113442000" -context "sdk\\\\application/1450113444000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1450113444000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1450113444000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1450113444000"
webtalk_transmit -clientid 1088496066 -regid "211101974_0_0_504" -xml /home/fel/Vivado_Projects/wSumIntegration/wSumIntegration.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/fel/Vivado_Projects/wSumIntegration/wSumIntegration.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/fel/Vivado_Projects/wSumIntegration/wSumIntegration.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
