# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z010clg400-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/fel/zyboSimpleHDMI/hdmiPassThrough14.4/hdmiPassThrough14.4.cache/wt [current_project]
set_property parent.project_path /home/fel/zyboSimpleHDMI/hdmiPassThrough14.4/hdmiPassThrough14.4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths {
  /home/fel/zyboSimpleHDMI/ip_repo/sobel_filter_1.0
  /home/fel/zyboSimpleHDMI/ip/tbuf
  /home/fel/zyboSimpleHDMI/ip/hdmi_rx_v1_00_a
  /home/fel/sobel_test/src
  /home/fel
} [current_project]
add_files /home/fel/zyboSimpleHDMI/hdmiPassThrough14.4/hdmiPassThrough14.4.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/fel/zyboSimpleHDMI/hdmiPassThrough14.4/hdmiPassThrough14.4.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/fel/zyboSimpleHDMI/hdmiPassThrough14.4/hdmiPassThrough14.4.srcs/sources_1/bd/design_1/ip/design_1_sobel9_0_0/src/fifo_line1/fifo_line1/fifo_line1.xdc]
set_property used_in_implementation false [get_files -all /home/fel/zyboSimpleHDMI/hdmiPassThrough14.4/hdmiPassThrough14.4.srcs/sources_1/bd/design_1/ip/design_1_sobel9_0_0/src/fifo_line1/fifo_line1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fel/zyboSimpleHDMI/hdmiPassThrough14.4/hdmiPassThrough14.4.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/fel/zyboSimpleHDMI/hdmiPassThrough14.4/hdmiPassThrough14.4.srcs/sources_1/bd/design_1/design_1.bd]

read_vhdl -library xil_defaultlib /home/fel/zyboSimpleHDMI/hdmiPassThrough14.4/hdmiPassThrough14.4.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
read_xdc /home/fel/zyboSimpleHDMI/hdmiPassThrough14.4/hdmiPassThrough14.4.srcs/constrs_1/new/hdmi.xdc
set_property used_in_implementation false [get_files /home/fel/zyboSimpleHDMI/hdmiPassThrough14.4/hdmiPassThrough14.4.srcs/constrs_1/new/hdmi.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file design_1_wrapper.hwdef }
synth_design -top design_1_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
